### ISSUE TITLE
An error README.md

### ISSUE THREAD

**Issue by kighting** [pbeshai/d3-interpolate-path#19]
Hi Peter,

Thank you much to make this plugin! It works really nice!!

I found one error in your README.md. In the **Example Usage** part:
d3.select('path.my-path')
  .transition()
  .duration(2000)
  .attrTween('d', function (d) {
    var previous = d3.select(this).attr('d');
    var current = line(d);
    return **d3**.interpolatePath(previous, current);
  });

The last line "return **d3**.interpolatePath(previous, current);" should be "return interpolatePath(previous, current);"

Not sure if it's because of my project setup but I couldn't get it working before deleting "d3". :)

**Comment by pbeshai** [comment]
Hi!

If you are importing it via a module system e.g. `import interpolatePath from 'd3-interpolate-path'`, you will need to use interpolatePath directly, but if you are just including the built js on your page, it gets packaged under the d3 namespace as the example shows.

**Comment by kighting** [comment]
Ya you are right! I'm using the module system. Thanks for the explanation!
