### ISSUE TITLE
Cannot import as stated in readme.md

### ISSUE THREAD

**Issue by spoldman** [pbeshai/d3-interpolate-path#20]
For some reason
`import { interpolatePath } from 'd3-interpolate-path'` 
returns undefined for interpolatePath 

if I do 
`import * as d3interpolatePath from 'd3-interpolate-path'`
d3interpolatePath returns 
`{
   d3: {
      interpolatePath: function....
   }
}
`

And if I do use that interpolatePath function it returns 
Uncaught TypeError: d3Interpolate.interpolateString is not a function

Even though I have 'd3-interpolate' installed in my node_modules folder

**Comment by pbeshai** [comment]
Interesting. Can you share the code of your project or explain your build system?

**Comment by spoldman** [comment]
It is a pretty big and complex codebase split into monorepo so it will probably be hard to share some code. 
Just so you get the idea we are using lerna and yarn workspaces. We use webpack and babel to build our code. Maybe it has something to do with yarn workspaces or something with our build system

Maybe I should take some time to investigate a bit further and see if I can come up with something.

**Comment by pbeshai** [comment]
Hmm, I don't have any experience with workspaces. I use the import as described without any issue in my webpack+yarn projects. The error sounds like it is failing to resolve my require('d3-interpolate') dependency, and it's weird the way it is nesting D3 in there. Perhaps I need to update rollup to accommodate these workspaces? Not sure, but would be helpful to have a test case.

Here's the generated code it tries to run on import: https://github.com/pbeshai/d3-interpolate-path/blob/master/docs/d3-interpolate-path.js

**Comment by spoldman** [comment]
I think I have found the error. It had something to do with a bad regex on the babel-loader that caused it to run through babel twice.
Sorry for all the trouble and thanks for the help

**Comment by pbeshai** [comment]
Cool, thanks for the follow-up!
