### ISSUE TITLE
Unexpected token name «i», expected punc «;»

### ISSUE THREAD

**Issue by J28848** [pbeshai/d3-interpolate-path#21]
seem v2.0.1 is src that I installed from `npm` , it is not a build version. my project compile the `js` files with babel ignore all the files in `node_modules`, so I encounter the errors:

``` shell
Unexpected token name «i», expected punc «;»
```

**Comment by pbeshai** [comment]
I'm not sure I understand what you're saying. Can you provide more context around this error?
