### ISSUE TITLE
Request for code that is `<script src=...` compatible. 

### ISSUE THREAD

**Issue by wolfiex** [pbeshai/d3-interpolate-path#22]
<script src="https://peterbeshai.com/d3-interpolate-path/d3-interpolate-path.js"></script>

for example.

**Comment by pbeshai** [comment]
The zips in the [Releases](https://github.com/pbeshai/d3-interpolate-path/releases) section should work or were you hoping for a CDN hosted version?

**Comment by wolfiex** [comment]
Ah, the phrase within the README should have been somewhere in there.  Just for completeness / quick reference. The link to your website (above) would suffice, although admittedly you may not want the unnecessary traffic.
