### ISSUE TITLE
Thank you ❤️

### ISSUE THREAD

**Issue by wcandillon** [pbeshai/d3-interpolate-path#23]
It took me a while to find your package but I just wanted to write you a big thank you for writing this package. Many packages like this one exist but they all have either strong coupling with the DOM or some other 2d library. I just needed what your library provides.

It took me a while to find this lib. After some time, I decided to focus my research on the d3 ecosystem since d3 libs seems to always be nicely decoupled from any rendering system. And then I found this great package.

Thank you 🙋🏼‍♂️

**Comment by pbeshai** [comment]
Aw thanks for sharing!
