### ISSUE TITLE
Can this be used with Canvas/WebGL?

### ISSUE THREAD

**Issue by richardwestenra** [pbeshai/d3-interpolate-path#35]
Hey, we are using this on [Kedro-Viz](https://github.com/quantumblacklabs/kedro-viz) to great effect, but we've been finding that our transitions and rendering are very slow on large graphs, so I've been considering switching the SVG rendering to Canvas/WebGL. But I'd need to find alternatives for all of our functionality first.

From a look over the code, this library appears to convert SVG path `d` attribute strings into arrays of x/y points, then interpolate them, then convert them back to SVG strings again. But if I wanted to just pass it two pure arrays of points and have it process them as is without converting to/from SVG strings, is there a mechanism to do that? Looks like there might be some private functions to do it but I can't identify exactly where. If it's reasonably doable, would you be happy to expose and document it?

e.g. something like:

```es6
import { interpolateRawPath } from 'd3-interpolate-path';

var previous = [[0,0], [50,50]];
var next = [[10,10], [10,20], [150,150]];
var current = interpolateRawPath(previous, next)(0.5);
```

Thanks for your work on this, I really appreciate it!

**Comment by pbeshai** [comment]
Good idea, resolved in v2.2.0
