### ISSUE TITLE
Arc path

### ISSUE THREAD

**Issue by pinoycamper** [pbeshai/d3-interpolate-path#39]
Will this work if the path contains arc? I will still have to try this.

**Comment by pbeshai** [comment]
It should be okay interpolating between two paths with arcs. If the index of the arc commands in the `d` strings are different, it will still work but it will probably look a bit weird, or if the two paths have different number of points. Best to just try and see what happens :) 

The interpolator has special case handling for bezier curves and works very well with lines, but I haven't put efforts into the `A` command when the paths have different numbers of points.
