### ISSUE TITLE
Support breaks in Paths

### ISSUE THREAD

**Issue by IPWright83** [pbeshai/d3-interpolate-path#45]
D3 line rendering functions offer a `defined()` function which can be used to split up paths where there is no value. The path interpolation however doesn't handle this very nicely.

Could we extend to include support so `defined()` works correctly?

**Comment by pbeshai** [comment]
Do you have any examples available? Maybe in code sandboxes? It's not necessarily obvious to me the best way to go about this type of interpolation. I might consider splitting your before/after path strings into segments (e.g. split on 'M') and running interpolation on them directly.

**Comment by IPWright83** [comment]
I don't have an example in a sandbox at the moment, but I can share some setup. Here's a recording of the animations - lines aren't too bad to be honest, areas are pretty ugly though.

![Paths](https://user-images.githubusercontent.com/1374775/129863755-c41cefac-45e0-4d42-94f8-dcd9d477872f.gif)

My data set is transitioning from:
```
[
    { x: 5, y: 4, y2: 10 },
    { x: 2, y: 6, y2: 8 },
    { x: 20, y: 11, y2: 6 },
]
```
to
```
[
    { x: 5, y: 4, y2: 10 },
    { x: 2, y: 6, y2: 8 },
    { x: 9, y: 6, y2: 10 },
    { x: 11, y: null, y2: 10 },
    { x: 15, y: 7, y2: 10 },
    { x: 20, y: 11, y2: 6 },
]
```

**Line**
```
const sortedData = data.sort((a, b) => d3.ascending(a.x, b.x));
const line = d3
            .line()
            .x((d) => xScale(d.x))
            .y((d) => yScale(d.y))
            .defined((d) => d.y !== null && d.y !== undefined);

d3.select("svg")
            .select("path")
            .datum(sortedData)
            .transition("line")
            .duration(500)
            .attrTween("d", function (d) {
                const previous = d3.select(this).attr("d");
                const current = line(d);
                return interpolatePath(previous, current);
            })
            .style("stroke", "steelblue");
```

**Area**
```
const sortedData = data.sort((a, b) => d3.ascending(a.x, b.x));
const area = d3
            .area()
            .curve(d3.curveLinear)
            .x((d) => xScale(d.x))
            .y0((d) => yScale.range()[0]))
            .y1((d) => yScale(d.y))
           .defined((d) => d.y !== null && d.y !== undefined);

 d3.select("svg)
            .select("path")
            .datum(sortedData)
            .style("fill", "steelblue")
            .style("stroke", "steelblue")
            .style("fill-opacity", 0.5)
            .style("pointer-events", "none")
            .transition("area")
            .duration(500)
            .attrTween("d", function (d) {
                const previous = d3.select(this).attr("d");
                const current = area(d);
                return interpolatePath(previous, current, (a, b) => {
                    return a.x === b.x && a.x === xScale.range()[1];
                });
            });
```

**Comment by pbeshai** [comment]
Here's an example you can try and tweak to get results you like https://codesandbox.io/s/d3-interpolate-path-multi-example-8l32q

![Aug-24-2021 15-58-03](https://user-images.githubusercontent.com/793847/130700690-cba25624-a8c0-4602-95c7-b94319627bd8.gif)

**Comment by IPWright83** [comment]
Thanks @pbeshai that's really helpful. I'm going to close this issue as that's sorted me out, but feel free to re-open if you think it should be built into the library itself.
