### ISSUE TITLE
Add support for extensions on final value

### ISSUE THREAD

**Issue by andyrichardson** [pbeshai/d3-interpolate-path#47]
Hey there, thanks for the library!

I'm wondering if you would consider adding support for getting the final value with extensions? I'm looking to use a CSS transition to go from one path to another but the [omission of extensions](https://github.com/pbeshai/d3-interpolate-path/blob/master/src/interpolatePath.js#L387) on the final value breaks this.

Using the example from the readme, here's a visual

```js
const p1 = 'M0,0 L10,10'
const p2 = 'M10,10 L20,20 L30,30'

// This works as expected
const i1 = interpolatePath(p1, p2);
i1(0)   // 'M0,0 L10,10 L10,10'
i1(1)   // 'M10,10 L20,20 L30,30'

// Switching path order, the final value is no longer extended
const i2 = interpolatePath(p2, p1);
i2(0)   // 'M10,10 L20,20 L30,30'
i2(1)   // 'M0,0 L10,10'
```

It would be great if, in this example, `i2(1)` returned the same value as `i1(0)` (`'M0,0 L10,10 L10,10'`) so that paths are always normalized.

> **Note**
> For anyone else with this issue, providing an "almost 1" value can be used as a workaround  (e.g. `interpolator(1.000001)`)

**Comment by pbeshai** [comment]
Hey sorry for the delay but this is now in v2.3.0. thanks for your help!
